NoNewPlayers: -1
announcement: ""
blockLogWorlds: []
disableCancelRestart: []
disableElderGuardians: []
disableSelectors: true
disabledCmds: []
logNonPlayerCmds: true
nonplayerCmds: []
oponlyCmds: []
projectileOwnerMaxDistance: 300
