name: Misc
main: org.c4k3.Misc.Misc
version: 1 #1.3.2R01
author: C4K3.org
description: Various miscellaneous features
commands:
  coords:
    description: Prints basic information about user coords to sender
  rules:
    description: Prints the server rules to sender
  follow:
    description: Sets creative, activates vanish and teleports OPs to target player
  goback:
    description: Lets OPs go back to wherever they came from after using follow