name: Misc
main: org.c4k3.Misc.Misc
version: 1.1 #1.4.6B1
author: C4K3.org
description: Various miscellaneous features
commands:
  coords:
    description: Prints basic information about user coords to sender
  f:
    description: Sets creative, activates vanish and teleports OPs to target player
  b:
    description: Lets OPs go back to wherever they came from after using follow
  a:
    description: Sends a message to all other OPs on the server (private chat channel)
  tp:
    description: Teleports command sender to target player (autofills names)
  tps:
    description: Teleports target player to commandsender (autofills names)
  tpc:
    description: Teleports command sender to target coordinates
  tpw:
    description: Teleports command sender to spawn of target world